services:
  customers-service:
    image: springcommunity/spring-petclinic-customers-service
    container_name: customers-service
    deploy:
      resources:
        limits:
          memory: 512M
    # depends_on:
    #   config-server:
    #     condition: service_healthy
    #   discovery-server:
    #     condition: service_healthy
    ports:
    - 8081:8081

  visits-service:
    image: springcommunity/spring-petclinic-visits-service
    container_name: visits-service
    deploy:
      resources:
        limits:
          memory: 512M
    # depends_on:
    #   config-server:
    #     condition: service_healthy
    #   discovery-server:
    #     condition: service_healthy
    ports:
     - 8082:8082

  vets-service:
    image: springcommunity/spring-petclinic-vets-service
    container_name: vets-service
    deploy:
      resources:
        limits:
          memory: 512M
    # depends_on:
    #   config-server:
    #     condition: service_healthy
    #   discovery-server:
    #     condition: service_healthy
    ports:
     - 8083:8083


  # api-gateway:
  #   image: springcommunity/spring-petclinic-api-gateway
  #   container_name: api-gateway
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 512M
  #   depends_on:
  #     config-server:
  #       condition: service_healthy
  #     discovery-server:
  #       condition: service_healthy
  #   ports:
  #    - 8080:8080

  
  # admin-server:
  #   image: springcommunity/spring-petclinic-admin-server
  #   container_name: admin-server
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 512M
  #   depends_on:
  #     config-server:
  #       condition: service_healthy
  #     discovery-server:
  #       condition: service_healthy
  #   ports:
  #    - 9090:9090

  ## Grafana / Prometheus

  